esphome:
  name: hs-dustboy
  friendly_name: HS-dustboy
 

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
    level: DEBUG

# Enable Home Assistant API
api:
  # encryption:
    # key: "nQMmzUEN+N7nkJwWf5tPd5evtEJml4S7iRDhpaLN9xU="

ota:
  - platform: esphome
    password: "2c59133fe0c5c7ca47173d0e5d286400"

wifi:
  ssid: "@UNISERV-CMU_2.4G"
  #password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hs-Dustboy Fallback Hotspot"
    password: "12345678"

captive_portal:

web_server:
  version: 3


output:
  - platform: ledc
    pin: 21
    id: backlight_pwm
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: RESTORE_AND_ON   



spi:
  - id: lcd
    clk_pin: 14 # TFT_SCLK
    mosi_pin: 13 # TFT_MOSI
  # - id: touch
  #   clk_pin: 25 # TFT_SCLK
  #   mosi_pin: 32 # TFT_MOSI
  #   miso_pin: 39 # Not used for this display

# ILI9XXX display configuration
display:
  - platform: ili9xxx
    model: ILI9341
    spi_id: lcd
    cs_pin: 15 # TFT_CS
    dc_pin: 2 # TFT_DC
    reset_pin: 12 # TFT_RST
    # rotation: 90
    # auto_clear_enabled: True
    invert_colors: false
    #show_test_card: True
    id: my_display
    pages:
        - lambda:
            it.image(0, 0, id(esphome_logo));
    color_palette: 8BIT

image:
  - file: A.png
    type: rgb565
    id: esphome_logo
    resize: 200x162


font:
  - file:
      type: gfonts
      family: "Kanit"
    id: fntXS_Kanit
    size: 8    



i2c:
  sda: 27
  scl: 22
  scan: true
  id: bus_a
